<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <LiveStudioDiagnosticsEndpoint Condition="'$(LiveStudioDiagnosticsEndpoint)' == ''"></LiveStudioDiagnosticsEndpoint>
  </PropertyGroup>
  <ItemGroup>
    <AssemblyMetadata Include="LiveStudioDiagnosticsEndpoint" Value="$(LiveStudioDiagnosticsEndpoint)" />
  </ItemGroup>
</Project>
